#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required


##################
# Before install #
##################
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  
################
# build matrix #
################
matrix:
  include:
    # GCC 4.9
    - compiler: gcc-4.9
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9    
      before_script: export CXX=g++-4.9

    # GCC 5
    - compiler: gcc-5
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_script: export CXX=g++-5

    # Clang 3.9 and static analysis
    - os: linux
      compiler: clang-3.9
      addons:
       apt:
         sources:
           - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
           - sourceline: 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
         packages:
           - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - CONFIG=scan-build
        - ASAN="ON"
        - MSAN="ON"
        - TSAN="ON"
        - UBSAN="ON"
        - STATIC_ANALYZER="ON"
        - CLANG_FORMAT="ON"
        - CLANG_TIDY="ON"
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang-3.9
      after_success:
        - scan-build-3.9 cmake ..
        - scan-build-3.9 cd .. && make

    # Valgrind and cppcheck
    - compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=valgrind
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cppcheck', 'valgrind']
      before_script: export CXX=g++-5
      after_success:
        # - valgrind --error-exitcode=1 --leak-check=full ./lem
        - valgrind --error-exitcode=1 --leak-check=full ./lemtest
        - cd .. && cppcheck --enable=warning --inconclusive --force --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1

    # OSX / Clang
    - os: osx
      osx_image: xcode7.3
      before_install:
        - brew update

    - os: osx
      osx_image: xcode8
      before_install:
        - brew update

################
# build script #
################

script:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..
    - make
